### ISSUE TITLE
LinkedIn

### ISSUE THREAD

**Issue by v0idpwn** [abhijithvijayan/sherlock#5]
Apparently, LinkedIn doesn't let you look at profiles if you don't have an account, but you are able to check their existence.

**Comment by abhijithvijayan** [comment]
@v0idpwn Thanks for noticing. I will add site to it soon.

**Comment by v0idpwn** [comment]
@abhijithvijayan I was adding it myself, but it returns 999...

**Comment by abhijithvijayan** [comment]
@v0idpwn I couldn't find LinkedIn in the original sherlock site list file https://github.com/TheYahya/sherlock/blob/master/sites.md

might be coz of the auth wall. axios package can't get the redirected url as of now, so if the site gets redirected, there is no reliable way to check for the existence, that's why parsing html and status code checking could only be used here. 

free to submit PRs if succeed. thanks.

**Comment by v0idpwn** [comment]
@abhijithvijayan That's awful... I'm pretty sure there are possible workarounds but I wont work on this now. Why does LinkedIn sucks so much? :yum:

**Comment by abhijithvijayan** [comment]
@v0idpwn haha, lol.
